#server:
#  port: 8080
#
#spring:
#  application:
#    name: anynote-gateway
#  cloud:
#    gateway:
#      routes:
#        # 系统模块
#        - id: anynote-system
#          uri: http://localhost:9201/
#          predicates:
#            - Path=/system/**
#          filters:
#            - StripPrefix=1